export type AdUnit = {
  id: string;
  category: string;
  headline: string;
  body: string;
  cta: string;
  bgColor: string;
  textColor: string;
  accentColor: string;
  size: 'small' | 'medium' | 'banner';
};

export const AD_POOLS: Record<string, AdUnit[]> = {
  portfolio: [
    {
      id: 'port-1', category: 'portfolio',
      headline: 'HireMe.biz — Get Hired in 24 Hours (or Your Resume Back)',
      body: 'Our algorithm matches you with jobs you\'re underqualified for. Guaranteed interviews or we blame the economy.',
      cta: 'Upload Resume Now',
      bgColor: '#0D1117', textColor: '#C9D1D9', accentColor: '#238636',
      size: 'small',
    },
    {
      id: 'port-2', category: 'portfolio',
      headline: 'ResumeBlaster Pro — Blast Your CV to 10,000 Recruiters Who Will Ignore It',
      body: 'Maximum exposure. Minimum results. Your resume, everywhere, read by nobody.',
      cta: 'Blast My Resume',
      bgColor: '#161B22', textColor: '#E6EDF3', accentColor: '#1F6FEB',
      size: 'small',
    },
    {
      id: 'port-3', category: 'portfolio',
      headline: 'LinkedOut — The Anti-LinkedIn for People Who Hate Networking',
      body: 'Connect with professionals who also hate connecting with professionals. Zero endorsements. Maximum authenticity.',
      cta: 'Join LinkedOut',
      bgColor: '#0A0E1A', textColor: '#A8B2D8', accentColor: '#64FFDA',
      size: 'medium',
    },
    {
      id: 'port-4', category: 'portfolio',
      headline: 'SkillFaker™ — Add Any Skill to Your Resume Instantly',
      body: '"Proficient in Kubernetes" — added in 3 clicks. No experience required. Legally ambiguous.',
      cta: 'Fake My Skills',
      bgColor: '#1A0A0A', textColor: '#FFB3B3', accentColor: '#FF4444',
      size: 'small',
    },
    {
      id: 'port-5', category: 'portfolio',
      headline: 'InterviewCoach.ai — We Guarantee You\'ll Sound Confident (Results May Vary)',
      body: 'AI-powered coaching that teaches you to say "synergy" and "bandwidth" with conviction.',
      cta: 'Sound Confident Now',
      bgColor: '#0A1A0A', textColor: '#B3FFB3', accentColor: '#44FF44',
      size: 'small',
    },
    {
      id: 'port-6', category: 'portfolio',
      headline: 'PortfolioHosting.net — 99.9% Uptime Unless It Rains',
      body: 'Your portfolio, online almost always. Weather-dependent SLA. Servers located in a shed.',
      cta: 'Host My Portfolio',
      bgColor: '#0A0A1A', textColor: '#B3B3FF', accentColor: '#4444FF',
      size: 'small',
    },
    {
      id: 'port-7', category: 'portfolio',
      headline: 'CareerPivot™ — Become a Web3 Influencer in 30 Days',
      body: 'No experience in Web3? Perfect. Neither do most Web3 influencers. Start posting today.',
      cta: 'Pivot My Career',
      bgColor: '#1A0A1A', textColor: '#FFB3FF', accentColor: '#FF44FF',
      size: 'medium',
    },
  ],
  startup: [
    {
      id: 'start-1', category: 'startup',
      headline: 'PitchDeck.ai — Generate 47 Slides of Buzzwords Instantly',
      body: 'TAM: $4 trillion. Moat: Vibes. Exit strategy: Acqui-hire. Deck ready in 60 seconds.',
      cta: 'Generate My Deck',
      bgColor: '#0D0D1A', textColor: '#E0E0FF', accentColor: '#7C3AED',
      size: 'small',
    },
    {
      id: 'start-2', category: 'startup',
      headline: 'GrowthHack Pro — 10x Your DAUs With One Weird Trick',
      body: 'VCs hate him. This founder grew from 12 to 120 users using a single dark pattern.',
      cta: 'Hack My Growth',
      bgColor: '#1A0D00', textColor: '#FFE0B3', accentColor: '#FF8C00',
      size: 'small',
    },
    {
      id: 'start-3', category: 'startup',
      headline: 'PivotConsult™ — We\'ll Tell You to Pivot (Flat Fee: $50k)',
      body: 'Our consultants will listen to your idea for 20 minutes and recommend pivoting to B2B SaaS.',
      cta: 'Book a Pivot Session',
      bgColor: '#001A0D', textColor: '#B3FFD9', accentColor: '#00CC66',
      size: 'medium',
    },
    {
      id: 'start-4', category: 'startup',
      headline: 'VCMatchmaker — Connect With Investors Who Will Ghost You',
      body: 'Access our network of 500+ VCs who will open your cold email and never respond. Premium ghosting.',
      cta: 'Get Ghosted Faster',
      bgColor: '#1A1A00', textColor: '#FFFFD9', accentColor: '#CCCC00',
      size: 'small',
    },
    {
      id: 'start-5', category: 'startup',
      headline: 'DisruptBot — Automate Your Disruption Pipeline',
      body: 'Schedule your disruptions. Automate your pivots. Set your paradigm shifts on autopilot.',
      cta: 'Automate Disruption',
      bgColor: '#1A000D', textColor: '#FFD9E8', accentColor: '#FF0066',
      size: 'small',
    },
    {
      id: 'start-6', category: 'startup',
      headline: 'ScaleOrFail™ — Move Fast, Break Things, Blame Interns',
      body: 'Enterprise-grade intern blame management. Automated scapegoating. GDPR compliant.',
      cta: 'Scale Now',
      bgColor: '#001A1A', textColor: '#D9FFFF', accentColor: '#00CCCC',
      size: 'small',
    },
    {
      id: 'start-7', category: 'startup',
      headline: 'Unicorn Insurance — Protect Your Valuation From Reality',
      body: 'When the market corrects, we correct your pitch deck. Valuation protection for the delusional founder.',
      cta: 'Insure My Unicorn',
      bgColor: '#0D001A', textColor: '#E8D9FF', accentColor: '#9900CC',
      size: 'medium',
    },
  ],
  product: [
    {
      id: 'prod-1', category: 'product',
      headline: 'BetterProduct™ — Literally Just Like Yours But Cheaper',
      body: 'We saw your product. We made it. It\'s $3 less. Sorry not sorry.',
      cta: 'Buy the Better One',
      bgColor: '#1A0A00', textColor: '#FFD9B3', accentColor: '#FF6600',
      size: 'small',
    },
    {
      id: 'prod-2', category: 'product',
      headline: 'ShipSafe Insurance — We Cover Lost Packages (Except Yours)',
      body: 'Comprehensive shipping insurance with a 47-page exclusions list. Your package is probably on there.',
      cta: 'Get Covered (Maybe)',
      bgColor: '#001A0A', textColor: '#B3FFD9', accentColor: '#00AA44',
      size: 'small',
    },
    {
      id: 'prod-3', category: 'product',
      headline: 'ReviewBoost™ — 500 Five-Star Reviews Overnight',
      body: 'Real reviews from real people who have never used your product. Authentically inauthentic.',
      cta: 'Boost My Reviews',
      bgColor: '#1A1A00', textColor: '#FFFFD9', accentColor: '#AAAA00',
      size: 'medium',
    },
    {
      id: 'prod-4', category: 'product',
      headline: 'CompetitorX — We Copied Your Idea and Did It Better',
      body: 'Imitation is the sincerest form of flattery. We flattered you so hard we raised $10M.',
      cta: 'See What We Copied',
      bgColor: '#1A000A', textColor: '#FFD9E8', accentColor: '#CC0044',
      size: 'small',
    },
    {
      id: 'prod-5', category: 'product',
      headline: 'ReturnAnything™ — No Questions Asked (Many Questions Asked)',
      body: 'Our hassle-free returns process involves 12 forms, 3 phone calls, and a notarized affidavit.',
      cta: 'Return Something',
      bgColor: '#000A1A', textColor: '#D9E8FF', accentColor: '#0044CC',
      size: 'small',
    },
    {
      id: 'prod-6', category: 'product',
      headline: 'DropshipKing — Sell Products You\'ve Never Seen',
      body: 'List 50,000 products from a warehouse in a country you can\'t find on a map. Entrepreneurship!',
      cta: 'Start Dropshipping',
      bgColor: '#0A1A00', textColor: '#D9FFB3', accentColor: '#66AA00',
      size: 'small',
    },
    {
      id: 'prod-7', category: 'product',
      headline: 'UnboxingFame — Pay Influencers to Pretend They Like It',
      body: 'Connect with micro-influencers who will enthusiastically unbox your product and never mention it again.',
      cta: 'Buy Fake Enthusiasm',
      bgColor: '#1A001A', textColor: '#FFD9FF', accentColor: '#AA00AA',
      size: 'medium',
    },
  ],
  finance: [
    {
      id: 'fin-1', category: 'finance',
      headline: 'GuaranteedReturns.biz — 400% APY (Not Financial Advice)',
      body: 'Totally real returns. Definitely not a Ponzi scheme. Our lawyers made us say that last part.',
      cta: 'Get 400% Returns',
      bgColor: '#001A00', textColor: '#B3FFB3', accentColor: '#00CC00',
      size: 'small',
    },
    {
      id: 'fin-2', category: 'finance',
      headline: 'AstroTrader™ — Mercury Retrograde Signals for Day Trading',
      body: 'When Mercury goes retrograde, sell everything. When Venus aligns with Mars, buy meme stocks. Science.',
      cta: 'Trade With the Stars',
      bgColor: '#0A001A', textColor: '#D9B3FF', accentColor: '#7700CC',
      size: 'small',
    },
    {
      id: 'fin-3', category: 'finance',
      headline: 'CryptoMaster Course — Learn to Lose Money Faster',
      body: '47 hours of video content teaching you to HODL through every dip until there\'s nothing left to HODL.',
      cta: 'Enroll Now ($997)',
      bgColor: '#1A0A00', textColor: '#FFD9B3', accentColor: '#FF8800',
      size: 'medium',
    },
    {
      id: 'fin-4', category: 'finance',
      headline: 'TaxAvoidance.legal — Technically Legal in 3 Countries',
      body: 'Our offshore structure is completely above board in jurisdictions that don\'t share data with yours.',
      cta: 'Avoid Taxes Legally',
      bgColor: '#001A1A', textColor: '#B3FFFF', accentColor: '#00AAAA',
      size: 'small',
    },
    {
      id: 'fin-5', category: 'finance',
      headline: 'RetirementNow™ — Retire at 25 With Our 47-Step System',
      body: 'Step 1: Have rich parents. Steps 2-47: Our proprietary system. Results not typical.',
      cta: 'Retire Immediately',
      bgColor: '#1A1A00', textColor: '#FFFFD9', accentColor: '#CCAA00',
      size: 'small',
    },
    {
      id: 'fin-6', category: 'finance',
      headline: 'NFT Advisor Pro — We\'ll Tell You Which JPEGs to Buy',
      body: 'Our AI analyzes monkey pictures and tells you which ones will appreciate. Spoiler: none of them.',
      cta: 'Buy Some JPEGs',
      bgColor: '#1A001A', textColor: '#FFB3FF', accentColor: '#CC00CC',
      size: 'small',
    },
    {
      id: 'fin-7', category: 'finance',
      headline: 'HedgeFundBot — Algorithmic Trading With Vibes-Based AI',
      body: 'Our AI reads the room. When the vibes are off, it sells. When the vibes are immaculate, it buys.',
      cta: 'Trade on Vibes',
      bgColor: '#00001A', textColor: '#B3B3FF', accentColor: '#0000CC',
      size: 'medium',
    },
  ],
  local: [
    {
      id: 'local-1', category: 'local',
      headline: 'BetterCoffee™ — The Shop Across the Street (We\'re Better)',
      body: 'Our baristas also can\'t spell your name correctly, but our cups have a nicer font.',
      cta: 'Come In (We\'re Better)',
      bgColor: '#1A0A00', textColor: '#FFD9B3', accentColor: '#CC6600',
      size: 'small',
    },
    {
      id: 'local-2', category: 'local',
      headline: 'YelpKiller™ — Review Platform With Even More Fake Reviews',
      body: 'Why settle for some fake reviews when you can have ALL fake reviews? Premium authenticity.',
      cta: 'Get Fake Reviews',
      bgColor: '#1A0000', textColor: '#FFB3B3', accentColor: '#CC0000',
      size: 'small',
    },
    {
      id: 'local-3', category: 'local',
      headline: 'FranchiseNow™ — Own a Business Without Any Ideas',
      body: 'We have the ideas. You have the money. Together we\'ll make something mediocre.',
      cta: 'Buy a Franchise',
      bgColor: '#001A00', textColor: '#B3FFB3', accentColor: '#00AA00',
      size: 'medium',
    },
    {
      id: 'local-4', category: 'local',
      headline: 'LocalSEO Pro — Rank #1 on Google Maps (Temporarily)',
      body: 'We\'ll get you to #1 for 3 weeks before Google updates their algorithm and you disappear forever.',
      cta: 'Rank #1 Briefly',
      bgColor: '#00001A', textColor: '#B3B3FF', accentColor: '#0000AA',
      size: 'small',
    },
    {
      id: 'local-5', category: 'local',
      headline: 'DeliveryDash™ — We\'ll Deliver It Eventually',
      body: 'Estimated delivery: sometime today, probably. Our drivers are "in the area" (they\'re not).',
      cta: 'Order for Delivery',
      bgColor: '#1A1A00', textColor: '#FFFFD9', accentColor: '#AAAA00',
      size: 'small',
    },
    {
      id: 'local-6', category: 'local',
      headline: 'CompetingBakery™ — Our Croissants Are Flakier (Probably)',
      body: 'We haven\'t tried your croissants but we\'re confident ours are better. Confidence is key.',
      cta: 'Try Our Croissants',
      bgColor: '#1A0A0A', textColor: '#FFD9D9', accentColor: '#CC4444',
      size: 'small',
    },
    {
      id: 'local-7', category: 'local',
      headline: 'SmallBizInsurance — Coverage for When Your Yelp Rating Tanks',
      body: 'One bad review can destroy a business. We can\'t stop that, but we can charge you monthly for sympathy.',
      cta: 'Insure My Rating',
      bgColor: '#0A1A0A', textColor: '#D9FFD9', accentColor: '#44CC44',
      size: 'medium',
    },
  ],
  event: [
    {
      id: 'event-1', category: 'event',
      headline: 'VirtualAlternative™ — Same Event But You Stay Home',
      body: 'All the content, none of the networking, zero of the free pens. Experience events from your couch.',
      cta: 'Attend Virtually',
      bgColor: '#001A1A', textColor: '#B3FFFF', accentColor: '#00CCCC',
      size: 'small',
    },
    {
      id: 'event-2', category: 'event',
      headline: 'NoShowInsurance™ — Get Paid When Nobody Comes',
      body: 'Protect your event revenue against the very real possibility that everyone RSVPs and nobody shows up.',
      cta: 'Insure My Event',
      bgColor: '#1A001A', textColor: '#FFB3FF', accentColor: '#CC00CC',
      size: 'small',
    },
    {
      id: 'event-3', category: 'event',
      headline: 'WebinarPlatform Pro — Host Meetings Nobody Attends in HD',
      body: '4K video quality for your 3-attendee webinar. Your empty waiting room has never looked so crisp.',
      cta: 'Host in 4K',
      bgColor: '#0A0A1A', textColor: '#D9D9FF', accentColor: '#4444CC',
      size: 'medium',
    },
    {
      id: 'event-4', category: 'event',
      headline: 'EventCancellation™ — Professional Excuse Generator',
      body: '"Due to unforeseen circumstances" — we have 47 variations. Force majeure templates included.',
      cta: 'Generate an Excuse',
      bgColor: '#1A0A00', textColor: '#FFD9B3', accentColor: '#CC7700',
      size: 'small',
    },
    {
      id: 'event-5', category: 'event',
      headline: 'TicketScalper™ — Legally Questionable Resale Platform',
      body: 'Buy low, sell high, operate in a legal grey area. Our terms of service are 47 pages for a reason.',
      cta: 'Scalp Some Tickets',
      bgColor: '#001A00', textColor: '#B3FFB3', accentColor: '#00BB00',
      size: 'small',
    },
    {
      id: 'event-6', category: 'event',
      headline: 'VenueBot — AI-Powered Empty Room Rental',
      body: 'Our AI finds you the perfect venue for your event. The AI cannot guarantee anyone will come.',
      cta: 'Find a Venue',
      bgColor: '#1A1A0A', textColor: '#FFFFD9', accentColor: '#BBBB00',
      size: 'small',
    },
    {
      id: 'event-7', category: 'event',
      headline: 'AttendanceInflator™ — Make 12 People Look Like 1,200',
      body: 'Strategic photography angles. Crowd sound effects. Stock photo attendees. Your event, packed (visually).',
      cta: 'Inflate Attendance',
      bgColor: '#0A001A', textColor: '#D9B3FF', accentColor: '#8800CC',
      size: 'medium',
    },
  ],
  campaign: [
    {
      id: 'camp-1', category: 'campaign',
      headline: 'PetitionPro™ — 1 Million Signatures (Mostly Bots)',
      body: 'Your cause deserves attention. Our bots will sign your petition 1 million times. Change is coming.',
      cta: 'Get Bot Signatures',
      bgColor: '#1A0000', textColor: '#FFB3B3', accentColor: '#CC0000',
      size: 'small',
    },
    {
      id: 'camp-2', category: 'campaign',
      headline: 'ProfessionalActivist™ — We Care About Your Cause (For a Fee)',
      body: 'Passionate advocacy, hourly rate. We\'ll be outraged on your behalf for $150/hour plus expenses.',
      cta: 'Hire an Activist',
      bgColor: '#001A00', textColor: '#B3FFB3', accentColor: '#00BB00',
      size: 'small',
    },
    {
      id: 'camp-3', category: 'campaign',
      headline: 'AwarenessCoach™ — Raise Awareness Without Doing Anything',
      body: 'Post. Share. React. Change your profile picture. Feel good about yourself. Nothing changes. Perfect.',
      cta: 'Raise Awareness',
      bgColor: '#00001A', textColor: '#B3B3FF', accentColor: '#0000BB',
      size: 'medium',
    },
    {
      id: 'camp-4', category: 'campaign',
      headline: 'ChangeOrg Premium — Your Petition But With Better Fonts',
      body: 'Same petition. Same government ignoring it. But now in Helvetica Neue. Premium tier: Bold.',
      cta: 'Upgrade Your Petition',
      bgColor: '#1A1A00', textColor: '#FFFFD9', accentColor: '#BBBB00',
      size: 'small',
    },
    {
      id: 'camp-5', category: 'campaign',
      headline: 'VirtualProtest™ — March From Your Couch',
      body: 'Upload a photo of yourself holding a sign. We\'ll composite you into a crowd. Activism, delivered.',
      cta: 'Protest Virtually',
      bgColor: '#1A001A', textColor: '#FFB3FF', accentColor: '#BB00BB',
      size: 'small',
    },
    {
      id: 'camp-6', category: 'campaign',
      headline: 'CauseInfluencer™ — Monetize Your Outrage',
      body: 'Turn your righteous anger into passive income. Sponsored outrage. Affiliate links to the revolution.',
      cta: 'Monetize My Cause',
      bgColor: '#001A1A', textColor: '#B3FFFF', accentColor: '#00BBBB',
      size: 'small',
    },
    {
      id: 'camp-7', category: 'campaign',
      headline: 'ImpactWashing™ — Look Like You\'re Helping (You\'re Not)',
      body: 'Corporate social responsibility without the responsibility. ESG scores without the E, S, or G.',
      cta: 'Wash My Impact',
      bgColor: '#0A1A0A', textColor: '#D9FFD9', accentColor: '#44BB44',
      size: 'medium',
    },
  ],
};

export const META_ADS: AdUnit[] = [
  {
    id: 'meta-1', category: 'meta',
    headline: 'Build Your Own Terrible Website',
    body: 'The Worst Website Generator. Same seed = same disaster.',
    cta: 'Generate Now (Free)',
    bgColor: '#0A0A0F', textColor: '#E0E0F0', accentColor: '#7C3AED',
    size: 'small',
  },
  {
    id: 'meta-2', category: 'meta',
    headline: 'Your Website Could Be This Bad',
    body: 'Professionally terrible. Seed-deterministic chaos. 15 section types.',
    cta: 'Try the Generator',
    bgColor: '#1A0A2E', textColor: '#C4B5FD', accentColor: '#A855F7',
    size: 'small',
  },
  {
    id: 'meta-3', category: 'meta',
    headline: 'WWG2 — Worst Website Generator',
    body: 'We spent months making something intentionally awful. You\'re welcome.',
    cta: 'Make Something Terrible',
    bgColor: '#0F0A1A', textColor: '#DDD6FE', accentColor: '#6D28D9',
    size: 'medium',
  },
  {
    id: 'meta-4', category: 'meta',
    headline: 'Chaos Level: Maximum',
    body: 'Ticker bars. Cookie banners. Exit popups. MIDI player. All at once.',
    cta: 'Experience the Chaos',
    bgColor: '#0A0A0F', textColor: '#E0E0F0', accentColor: '#7C3AED',
    size: 'small',
  },
];

export function getAdsForCategory(category: string, count: number): AdUnit[] {
  const pool = [...(AD_POOLS[category] ?? []), ...META_ADS];
  return pool.slice(0, count);
}
