import JSZip from 'jszip';
import type { Generation } from './chaos';
import { getSchemeById } from './color-schemes';
import { getSchemeById as getFontScheme } from './font-schemes';
import { selectBadInteractions, buildBadInteractionsCss, buildBadInteractionsJs } from './bad-interactions';

export async function downloadGeneratedZip(generation: Generation): Promise<void> {
  const colorScheme = getSchemeById(generation.settings.colorSchemeId);
  const fontScheme  = getFontScheme(generation.settings.fontSchemeId);

  const html = buildHtmlString(generation, colorScheme, fontScheme);
  const css  = buildCssString(colorScheme, fontScheme);

  const zip = new JSZip();
  zip.file('index.html', html);
  zip.file('styles.css', css);
  zip.file('README.txt', buildReadme(generation));

  const blob = await zip.generateAsync({ type: 'blob' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `disaster-${generation.seed}.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

function buildCssString(
  colorScheme: ReturnType<typeof getSchemeById>,
  fontScheme: ReturnType<typeof getFontScheme>
): string {
  const googleImport = fontScheme.googleFontsUrl
    ? `@import url('${fontScheme.googleFontsUrl}');\n\n`
    : '';

  return `${googleImport}/* Generated by The Force Awakens Website Generator */
/* Seed: (see index.html) */

:root {
  --bg:      ${colorScheme.background};
  --bg2:     ${colorScheme.backgroundSecondary};
  --surface: ${colorScheme.surface};
  --text:    ${colorScheme.text};
  --text2:   ${colorScheme.textSecondary};
  --muted:   ${colorScheme.textMuted};
  --a1:      ${colorScheme.accent1};
  --a2:      ${colorScheme.accent2};
  --a3:      ${colorScheme.accent3};
  --border:  ${colorScheme.border};
  --glow:    ${colorScheme.glow};
  --danger:  ${colorScheme.danger};
  --success: ${colorScheme.success};

  --font-heading: ${fontScheme.headingFamily};
  --font-body:    ${fontScheme.bodyFamily};
  --font-accent:  ${fontScheme.accentFamily};
}

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body { background: var(--bg); color: var(--text); font-family: var(--font-body); }
h1, h2, h3 { font-family: var(--font-heading); font-weight: 900; }

@keyframes blink { 0%,100% { opacity:1; } 50% { opacity:0; } }
.blink { animation: blink 0.8s step-end infinite; }
@keyframes pulse { 0%,100% { opacity:1; } 50% { opacity:0.5; } }
@keyframes marquee { from { transform: translateX(100vw); } to { transform: translateX(-100%); } }

section { padding: 4rem 2rem; border-bottom: 2px solid var(--border); }
button { cursor: pointer; font-family: var(--font-accent); }
a { color: var(--a1); }
`;
}

function buildHtmlString(
  generation: Generation,
  colorScheme: ReturnType<typeof getSchemeById>,
  fontScheme: ReturnType<typeof getFontScheme>
): string {
  // Compute active bad interactions at build time
  const activeEffects = selectBadInteractions(
    generation.seed,
    generation.settings.chaosLevel
  );
  const badCss = buildBadInteractionsCss(activeEffects);
  const badJs  = buildBadInteractionsJs(activeEffects, generation.seed);

  // Build section HTML from generation.sections
  const sectionsHtml = generation.sections.map(section => {
    switch (section.type) {
      case 'hero':
        return `
<section class="section-hero" style="text-align:center; padding:6rem 2rem; background:var(--bg);">
  <h1 style="font-size:clamp(2rem,6vw,4.5rem); color:var(--text); text-shadow:0 0 20px var(--glow); margin-bottom:1.5rem;">
    ${escHtml(generation.title)}
  </h1>
  <p style="font-size:1.2rem; color:var(--text2); margin-bottom:2rem; max-width:600px; margin-left:auto; margin-right:auto;">
    ${escHtml(generation.subtitle)}
  </p>
  <button style="background:var(--a1); color:var(--bg); padding:1rem 2.5rem; border:none; font-size:1.1rem; margin-right:1rem;">
    ${escHtml(generation.ctaPrimary)}
  </button>
  <button style="background:transparent; color:var(--a2); border:2px solid var(--a2); padding:1rem 2rem; font-size:1rem;">
    ${escHtml(generation.ctaSecondary)}
  </button>
</section>`;

      case 'features': {
        const items = (section.items ?? []).slice(0, section.itemCount);
        return `
<section style="background:var(--bg2,var(--bg)); padding:4rem 2rem;">
  <h2 style="text-align:center; color:var(--a1); font-size:2rem; margin-bottom:2rem;">${escHtml(section.headline)}</h2>
  <div style="display:grid; grid-template-columns:repeat(auto-fit,minmax(220px,1fr)); gap:1.5rem; max-width:1100px; margin:0 auto;">
    ${items.map(item => `
    <div style="background:var(--surface); border:2px solid var(--border); padding:1.5rem;">
      <div style="font-size:2rem; margin-bottom:0.75rem;">${item.icon ?? '🚀'}</div>
      <h3 style="color:var(--text); margin-bottom:0.5rem; font-size:1rem;">${escHtml(item.title)}</h3>
      <p style="color:var(--text2); font-size:0.9rem; line-height:1.5;">${escHtml(item.body)}</p>
    </div>`).join('')}
  </div>
</section>`;
      }

      case 'testimonials': {
        const items = (section.items ?? []).slice(0, section.itemCount);
        return `
<section style="background:var(--bg); padding:4rem 2rem;">
  <h2 style="text-align:center; color:var(--a1); font-size:2rem; margin-bottom:2rem;">${escHtml(section.headline)}</h2>
  <div style="display:grid; grid-template-columns:repeat(auto-fit,minmax(280px,1fr)); gap:1.5rem; max-width:900px; margin:0 auto;">
    ${items.map(item => `
    <div style="background:var(--surface); border:2px solid var(--a2); padding:1.5rem;">
      <p style="font-style:italic; color:var(--text); margin-bottom:1rem;">"${escHtml(item.body)}"</p>
      <strong style="color:var(--a2);">— ${escHtml(item.title)}</strong>
    </div>`).join('')}
  </div>
</section>`;
      }

      case 'form':
        return `
<section style="background:var(--bg); padding:4rem 2rem;">
  <div style="max-width:600px; margin:0 auto;">
    <h2 style="text-align:center; color:var(--a1); font-size:2rem; margin-bottom:2rem;">${escHtml(section.headline)}</h2>
    <form>
      ${(section.formFields ?? []).slice(0, section.itemCount).map(f => `
      <div style="margin-bottom:1rem;">
        <label style="display:block; color:var(--text2); font-size:0.85rem; margin-bottom:0.35rem;">${escHtml(f.label)}${f.required ? ' *' : ''}</label>
        <input type="${f.type === 'textarea' ? 'text' : f.type}" placeholder="${escHtml(f.placeholder ?? '')}"
          style="width:100%; padding:0.65rem; background:var(--surface); color:var(--text); border:2px solid var(--border);" />
      </div>`).join('')}
      <button type="submit" style="width:100%; padding:0.9rem; background:var(--a1); color:var(--bg); border:none; font-size:1rem; text-transform:uppercase;">
        Submit (You Cannot Unsend This)
      </button>
      <p style="text-align:center; font-size:0.72rem; color:var(--muted); margin-top:0.5rem;">
        By submitting, you agree to receive emails until the end of time.
      </p>
    </form>
  </div>
</section>`;

      case 'footer':
        return `
<footer style="background:var(--surface); border-top:4px solid var(--a1); padding:3rem 2rem 1.5rem; text-align:center;">
  <p style="color:var(--a1); font-size:1.1rem; margin-bottom:1rem;">${escHtml(section.body || 'All rights reserved (none)')}</p>
  <p style="font-size:0.65rem; color:var(--muted); max-width:700px; margin:0 auto;">
    * All claims on this website are estimates. Results may vary. Chaos Level: ${generation.settings.chaosLevel}/10.
    Generated by The Force Awakens Website Generator. Seed: ${generation.seed}.
  </p>
</footer>`;

      case 'pricing': {
        const items = (section.items ?? []).slice(0, section.itemCount);
        return `
<section style="background:var(--bg2,var(--bg));padding:4rem 2rem;">
  <h2 style="text-align:center;color:var(--a1);font-size:2rem;margin-bottom:2rem;">${escHtml(section.headline)}</h2>
  <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:1.5rem;max-width:900px;margin:0 auto;">
    ${items.map((item, i) => `
    <div style="background:var(--surface);border:3px solid ${i === 1 ? 'var(--a1)' : 'var(--border)'};padding:2rem;text-align:center;">
      <h3 style="color:var(--text);margin-bottom:0.5rem;">${escHtml(item.title)}</h3>
      <div style="font-size:2.5rem;font-weight:900;color:var(--a1);margin:1rem 0;">${escHtml(item.body)}</div>
      <button style="background:var(--a1);color:var(--bg);border:none;padding:0.75rem 1.5rem;width:100%;font-family:var(--font-accent);cursor:pointer;">GET IT NOW!!!</button>
    </div>`).join('')}
  </div>
</section>`;
      }

      case 'faq': {
        const items = (section.items ?? []).slice(0, section.itemCount);
        return `
<section style="background:var(--bg);padding:4rem 2rem;">
  <h2 style="text-align:center;color:var(--a1);font-size:2rem;margin-bottom:2rem;">${escHtml(section.headline)}</h2>
  <div style="max-width:700px;margin:0 auto;">
    ${items.map(item => `
    <details style="background:var(--surface);border:2px solid var(--border);margin-bottom:0.5rem;padding:1rem;">
      <summary style="cursor:pointer;color:var(--a1);font-weight:700;list-style:none;">${escHtml(item.title)}</summary>
      <p style="color:var(--text2);margin-top:0.75rem;line-height:1.6;">${escHtml(item.body)}</p>
    </details>`).join('')}
  </div>
</section>`;
      }

      case 'gallery': {
        const count = section.itemCount;
        return `
<section style="background:var(--bg2,var(--bg));padding:4rem 2rem;">
  <h2 style="text-align:center;color:var(--a1);font-size:2rem;margin-bottom:2rem;">${escHtml(section.headline)}</h2>
  <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;max-width:900px;margin:0 auto;">
    ${Array.from({length: count}).map((_, i) => `
    <div class="gallery-placeholder" style="aspect-ratio:4/3;background:var(--surface);border:2px dashed var(--border);display:flex;align-items:center;justify-content:center;color:var(--muted);font-size:0.85rem;">
      &#128247; Image ${i + 1}
    </div>`).join('')}
  </div>
</section>`;
      }

      case 'video':
        return `
<section style="background:var(--bg);padding:4rem 2rem;text-align:center;">
  <h2 style="color:var(--a1);font-size:2rem;margin-bottom:2rem;">${escHtml(section.headline)}</h2>
  <div class="video-placeholder" style="max-width:700px;margin:0 auto;aspect-ratio:16/9;background:var(--surface);border:4px solid var(--a1);display:flex;align-items:center;justify-content:center;font-size:4rem;color:var(--a1);">
    &#9654;
  </div>
  <p style="color:var(--muted);font-size:0.8rem;margin-top:0.75rem;">Video not available in downloaded version</p>
</section>`;

      case 'map':
        return `
<section style="background:var(--bg2,var(--bg));padding:4rem 2rem;text-align:center;">
  <h2 style="color:var(--a1);font-size:2rem;margin-bottom:2rem;">${escHtml(section.headline)}</h2>
  <div class="map-placeholder" style="max-width:900px;height:350px;margin:0 auto;background:var(--surface);border:4px solid var(--border);display:flex;flex-direction:column;align-items:center;justify-content:center;color:var(--muted);gap:0.5rem;">
    <span style="font-size:3rem;">&#128205;</span>
    <span>MAP GOES HERE</span>
    <span style="font-size:0.75rem;">(We don&#39;t actually know where we are)</span>
  </div>
</section>`;

      case 'stats': {
        const items = (section.items ?? []).slice(0, section.itemCount);
        return `
<section style="background:var(--bg);padding:4rem 2rem;">
  <h2 style="text-align:center;color:var(--a1);font-size:2rem;margin-bottom:2rem;">${escHtml(section.headline)}</h2>
  <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:1rem;text-align:center;max-width:900px;margin:0 auto;">
    ${items.map(item => `
    <div style="padding:1.5rem;">
      <div style="font-size:2.5rem;font-weight:900;color:var(--a1);font-family:var(--font-heading);">${escHtml(item.body)}</div>
      <div style="color:var(--muted);font-size:0.78rem;text-transform:uppercase;letter-spacing:0.08em;margin-top:0.5rem;">${escHtml(item.title)}</div>
      ${item.icon ? `<div style="color:var(--text2);font-size:0.75rem;font-style:italic;">${escHtml(item.icon)}</div>` : ''}
    </div>`).join('')}
  </div>
</section>`;
      }

      case 'team': {
        const items = (section.items ?? []).slice(0, section.itemCount);
        return `
<section style="background:var(--bg2,var(--bg));padding:4rem 2rem;">
  <h2 style="text-align:center;color:var(--a1);font-size:2rem;margin-bottom:2rem;">${escHtml(section.headline)}</h2>
  <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:1.5rem;text-align:center;max-width:1000px;margin:0 auto;">
    ${items.map(item => `
    <div style="background:var(--surface);border:2px solid var(--border);padding:2rem 1rem;">
      <div style="width:80px;height:80px;border-radius:50%;background:var(--a1);margin:0 auto 1rem;display:flex;align-items:center;justify-content:center;font-size:2rem;">&#128100;</div>
      <h3 style="color:var(--text);margin-bottom:0.25rem;">${escHtml(item.title)}</h3>
      <p style="color:var(--muted);font-size:0.8rem;">${escHtml(item.body)}</p>
    </div>`).join('')}
  </div>
</section>`;
      }

      case 'comparison': {
        const items = (section.items ?? []).slice(0, section.itemCount);
        return `
<section style="background:var(--bg);padding:4rem 2rem;">
  <h2 style="text-align:center;color:var(--a1);font-size:2rem;margin-bottom:2rem;">${escHtml(section.headline)}</h2>
  <table style="width:100%;max-width:700px;margin:0 auto;border-collapse:collapse;">
    <thead>
      <tr>
        <th style="padding:0.75rem;background:var(--surface);color:var(--muted);text-align:left;border:2px solid var(--border);">Feature</th>
        <th style="padding:0.75rem;background:var(--a1);color:var(--bg);text-align:center;border:2px solid var(--a1);">US &#10003;</th>
        <th style="padding:0.75rem;background:var(--surface);color:var(--text2);text-align:center;border:2px solid var(--border);">Them &#10007;</th>
      </tr>
    </thead>
    <tbody>
      ${items.map((item, i) => `
      <tr style="border-bottom:1px solid var(--border);">
        <td style="padding:0.75rem;color:var(--text);font-size:0.9rem;border:1px solid var(--border);">${escHtml(item.title)}</td>
        <td style="padding:0.75rem;text-align:center;color:var(--a1);font-size:1.2rem;border:1px solid var(--border);">&#10003;</td>
        <td style="padding:0.75rem;text-align:center;color:var(--muted);border:1px solid var(--border);">${i % 2 === 0 ? '&#10007;' : '???'}</td>
      </tr>`).join('')}
    </tbody>
  </table>
</section>`;
      }

      case 'blog-preview': {
        const items = (section.items ?? []).slice(0, section.itemCount);
        return `
<section style="background:var(--bg2,var(--bg));padding:4rem 2rem;">
  <h2 style="text-align:center;color:var(--a1);font-size:2rem;margin-bottom:2rem;">${escHtml(section.headline)}</h2>
  <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:1.5rem;max-width:1000px;margin:0 auto;">
    ${items.map(item => `
    <article style="background:var(--surface);border:2px solid var(--border);overflow:hidden;">
      <div style="height:120px;background:var(--a1);opacity:0.35;"></div>
      <div style="padding:1.5rem;">
        <h3 style="color:var(--text);margin-bottom:0.5rem;font-size:1rem;">${escHtml(item.title)}</h3>
        <p style="color:var(--text2);font-size:0.85rem;line-height:1.5;">${escHtml(item.body)}</p>
        <a href="#" style="color:var(--a1);font-size:0.85rem;display:inline-block;margin-top:0.75rem;text-decoration:none;">Read More &#8594;</a>
      </div>
    </article>`).join('')}
  </div>
</section>`;
      }

      case 'timeline': {
        const items = (section.items ?? []).slice(0, section.itemCount);
        return `
<section style="background:var(--bg);padding:4rem 2rem;">
  <h2 style="text-align:center;color:var(--a1);font-size:2rem;margin-bottom:2rem;">${escHtml(section.headline)}</h2>
  <div style="max-width:600px;margin:0 auto;border-left:4px solid var(--a1);padding-left:2rem;">
    ${items.map((item, i) => `
    <div style="margin-bottom:2rem;position:relative;">
      <div style="position:absolute;left:-2.6rem;width:1rem;height:1rem;border-radius:50%;background:var(--a1);top:0.2rem;border:2px solid var(--bg);"></div>
      <div style="color:var(--a2);font-size:0.78rem;font-weight:700;text-transform:uppercase;letter-spacing:0.1em;margin-bottom:0.2rem;">
        ${2010 + i * 2}
      </div>
      <h3 style="color:var(--text);margin-bottom:0.25rem;font-size:1rem;">${escHtml(item.title)}</h3>
      <p style="color:var(--text2);font-size:0.85rem;line-height:1.5;">${escHtml(item.body)}</p>
    </div>`).join('')}
  </div>
</section>`;
      }

      default:
        return `
<section style="padding:3rem 2rem; background:var(--bg2,var(--bg)); border-bottom:2px solid var(--border);">
  <h2 style="color:var(--a1); text-align:center; margin-bottom:1rem;">${escHtml(section.headline || section.type)}</h2>
</section>`;
    }
  }).join('\n');

  const tickerJs = generation.settings.interruptions.ticker ? `
<div id="ticker" style="position:fixed;top:0;left:0;right:0;height:36px;background:var(--a1);color:var(--bg);
overflow:hidden;display:flex;align-items:center;font-weight:700;font-size:0.85rem;z-index:9999;">
  <div id="ticker-content" style="white-space:nowrap;will-change:transform;">
    ⚡ WELCOME TO THIS WEBSITE ⚡ • IT IS VERY GOOD • ⚡ PLEASE STAY ⚡ • IT GETS BETTER • ⚡ WE PROMISE ⚡
  </div>
</div>
<script>
(function(){var c=document.getElementById('ticker'),t=document.getElementById('ticker-content');
if(!c||!t)return;var offset=c.offsetWidth,last=null;
function tick(now){if(!last)last=now;var d=(now-last)/1000;last=now;offset-=80*d;
if(offset<-t.scrollWidth)offset=c.offsetWidth;
t.style.transform='translateX('+Math.round(offset)+'px)';requestAnimationFrame(tick);}
requestAnimationFrame(tick);})();
</script>` : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escHtml(generation.title)}</title>
  <link rel="stylesheet" href="styles.css" />
  ${fontScheme.googleFontsUrl ? `<link rel="preconnect" href="https://fonts.googleapis.com" /><link rel="stylesheet" href="${fontScheme.googleFontsUrl}" />` : ''}
  ${badCss ? `<style>\n${badCss}\n</style>` : ''}
</head>
<body style="padding-top:${generation.settings.interruptions.ticker ? '36px' : '0'}">
  ${tickerJs}
  <main class="generated-page">
    ${sectionsHtml}
  </main>
  ${badJs ? `<script>\n${badJs}\n</script>` : ''}
  <!-- Generated by The Force Awakens Website Generator -->
  <!-- Seed: ${generation.seed} | Category: ${generation.settings.category} | Chaos: ${generation.settings.chaosLevel} -->
</body>
</html>`;
}

function buildReadme(generation: Generation): string {
  return `THE FORCE AWAKENS WEBSITE GENERATOR
=====================================

This website was programmatically generated to be deliberately bad.

Seed:      ${generation.seed}
Category:  ${generation.settings.category}
Layout:    ${generation.settings.layoutId}
Colors:    ${generation.settings.colorSchemeId}
Fonts:     ${generation.settings.fontSchemeId}
Chaos:     ${generation.settings.chaosLevel}/10
Version:   ${generation.version}

To reproduce this exact page, use seed ${generation.seed} in the generator.

This website intentionally violates UX best practices.
That's the whole point. We're proud of it. Sort of.

Files:
  index.html - The terrible website (includes chaos effects JS)
  styles.css - The terrible styles and color scheme
  README.txt - This file

Share your disaster: use seed ${generation.seed}
`;
}

function escHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
