import type { ContentPools } from "./content-pools";

export const portfolioContent: ContentPools = {
  hero: {
    headlines: [
      "I Am Available And Motivated (This Is Not A Threat)",
      "Your Next Best Employee, Pending Background Check",
      "Results-Oriented Human Being With Working Hands",
      "Hire Me Or Don't, But Mainly Hire Me",
      "Professional Since At Least 2017 (Ish)",
      "I Solve Problems You Didn't Know You Had And Some You Did",
      "Making Things Happen Since Before It Was Popular",
    ],
    subheadlines: [
      "Specializing in everything. Expert in most things. Familiar with the rest.",
      "5+ years of experience (counting the gap year, which was educational)",
      "Available immediately. Very immediately. Possibly too immediately.",
      "Currently between opportunities, by choice, mostly, for now",
      "Turning coffee into deliverables since [GRADUATION_YEAR]",
      "Open to relocation anywhere except places I don't want to go",
      "References available upon completion of rigorous selection process",
    ],
    cta_primary: [
      "Hire Me Now (Before You Think Too Hard About It)",
      "View My Work (I Curated It Carefully)",
      "Download CV (Warning: Contains Optimism)",
      "Contact Me (I Will Respond Immediately)",
      "See Portfolio (Trigger Warning: Excellence)",
    ],
    cta_secondary: [
      "I Also Have LinkedIn",
      "Or Don't — Your Loss",
      "Schedule Interview (Any Time Is Fine)",
      "Read Testimonials (Mostly Positive)",
      "View Skills (Self-Assessed)",
    ],
    badge_texts: [
      "⭐ AVAILABLE NOW",
      "🔥 ACTIVELY LOOKING",
      "✅ REFERENCES: YES",
      "💼 OPEN TO OFFERS",
      "🚀 READY TO SYNERGIZE",
    ],
  },
  features: {
    section_titles: [
      "Core Competencies (Self-Assessed)",
      "What I Bring To The Table (The Table May Vary)",
      "Skills & Abilities (See Footnotes)",
      "My Professional Superpowers™",
      "Things I Am Definitely Good At",
    ],
    card_headlines: [
      "Microsoft Word — Expert",
      "Meeting Attendance",
      "Synergy & Leveraging",
      "Problem Awareness",
      "Team Player (Debatable)",
      "Communication Skills",
      "Strategic Visioning",
      "Coffee Optimization",
      "Deadline Adjacency",
      "Stakeholder Management (Mainly Avoiding Them)",
    ],
    card_bodies: [
      "Proficient in creating documents that look professional from a distance",
      "Attended 40+ meetings in 2023. Contributed to 4. The other 36 are under investigation.",
      "World-class ability to synergize cross-functional paradigms into actionable deliverables",
      "Excellent at identifying problems. Solutions are a separate engagement.",
      "Works well with others when 'others' is defined broadly enough",
      "Can write emails. Has written many. Some were intentional.",
      "Capable of creating strategies so grand they require their own strategy",
      "Reduced team coffee costs by 0% through strategic personal consumption",
      "Consistently delivers projects near the deadline, often after it",
      "Manages stakeholders by ensuring they don't know what's happening",
    ],
    card_icons_labels: [
      "📊 Presented At: 2 Conferences (1 Was Voluntary)",
      "⚡ Response Time: Under 4 Hours (Business Days Only, Mostly)",
      "🏆 Awards: Self-Nominated, Pending Review",
    ],
  },
  testimonials: {
    section_titles: [
      "What People Are Saying (Selected Quotes)",
      "Professional References (Pre-Screened)",
      "Unsolicited Praise (Some Solicited)",
      "Social Proof (Technically Accurate)",
    ],
    quotes: [
      "I've never met anyone quite like [NAME]. That's not necessarily a compliment, but it's not a complaint.",
      "They show up. Every day. That's more than I can say for most.",
      "Genuinely tried their best. That's all any of us can ask for, really.",
      "Would hire again. Have hired again. Currently looking into why.",
      "Their work exceeded our expectations, which were admittedly quite low initially.",
      "A unique approach to problem-solving that I still think about sometimes.",
      "Always available to chat. Perhaps too available. But available.",
      "Delivered everything promised. Eventually. The eventual part was notable.",
      "Their presentation skills have improved noticeably since that first one.",
      "We found a role they're perfect for. It's being created as we speak.",
    ],
    names: ["Margaret T.", "Dave (former colleague)", "Anonymous (by request)", "J. Williams", "Dr. Something (PhD, retired)", "A. Person", "Mom", "LinkedIn Contact #847", "Previous Manager (name redacted)"],
    titles: ["VP of Something", "Director, Previously", "Colleague (indirect)", "Former Supervisor", "Team Lead (now elsewhere)", "Peer Reviewer", "Client (anonymous)", "Reference #3", "Professional Acquaintance"],
    companies: ["A Large Corporation", "That Startup (it pivoted)", "My Former Company", "A Place I Used To Work", "Confidential", "Previously Employed Ltd."],
    star_captions: ["5/5 (asked to round up from 4.2)", "⭐⭐⭐⭐⭐ (self-verified)", "4.8★ average (sample: 2)", "★★★★★ (one of these stars is aspirational)"],
  },
  about: {
    section_titles: ["About Me (The Short Version)", "My Professional Journey (Dramatic Arc)", "Who I Am (Professional Edition)", "The Origin Story (Work-Appropriate Version)"],
    paragraphs: [
      "I am a passionate and driven professional with a unique combination of skills that I'm still in the process of identifying. Over the years, I have grown significantly, especially in areas I didn't know needed growing. I bring enthusiasm, a reliable laptop, and the ability to find the conference room after only two wrong turns.",
      "My career began when I decided that my previous career was not ideal. Since then, I have accumulated experience across multiple industries, roles, and organizational structures, each of which has contributed to my holistic understanding of what not to do. I look forward to applying these learnings in a new context.",
      "I am results-oriented, which means I focus on results, when results are available. When results are unavailable, I focus on process, which is where the real results come from. I believe in continuous improvement, which is why I am continuously improving this bio.",
      "Described by colleagues as 'thorough' (2019), 'available' (2021), and 'still employed here' (2022), I bring a proven track record of track record-having to every role I undertake.",
    ],
  },
  stats: {
    labels: ["Projects Completed", "Happy Clients", "Years Experience", "Cups of Coffee", "Emails Sent", "Skills Listed"],
    values: ["47 (23 fully)", "12 (net)", "5+ (counting school)", "∞", "2,847", "94 (self-assessed)"],
    captions: ["*definition of 'completed' varies", "*net of complaints", "*school counts double", "*necessary for function", "*tracked since Q3 2020", "*see addendum for methodology"],
  },
  faq: {
    section_titles: ["Frequently Asked Questions", "Things People Ask Me", "Common Inquiries (With Answers)"],
    questions: ["Are you actually available?", "What is your salary expectation?", "Do you work well under pressure?", "What's your greatest weakness?", "Where do you see yourself in 5 years?", "Can you start immediately?", "Are your references real people?"],
    answers: ["Yes. Extremely yes. Please reach out.", "Competitive with market rate, which I define as slightly above whatever you're offering.", "I perform well under most types of pressure. Other types of pressure are still under evaluation.", "I care too much. Also I occasionally lose track of time when working on very interesting problems.", "At this organization. Ideally. Contributing meaningfully.", "Immediately is technically possible. 'Immediately immediately' may require 2 weeks notice.", "Yes. Margaret is my former manager. Dave is a former colleague. The third one is Mom but she has professional opinions."],
  },
  form: {
    section_titles: ["Get In Touch (Please)", "Contact Me — I Will Respond", "Send Me Opportunities", "Inquire Here (Open to Everything)"],
    field_labels: ["Your Name", "Company (Optional But Helpful)", "Role You're Hiring For", "Salary Range", "Message", "How You Found Me", "Timeline"],
    placeholders: ["First Last (or just First)", "Company LLC", "Something I'd be good at", "Competitive range preferred", "Tell me about this amazing opportunity...", "LinkedIn / Google / Desperation", "ASAP ideally"],
    submit_texts: ["Send Message", "Make Contact", "Submit Inquiry", "Reach Out", "Let's Talk (Seriously)"],
    success_messages: ["Message received! I will respond within 4 hours. I am setting a timer right now.", "Thank you! I have already started drafting a reply. It will be professional and enthusiastic.", "Sent! I saw this notification immediately. I am very available."],
    error_messages: ["Something went wrong. This is unusual for me specifically.", "Error. Please try again. I am standing by.", "Submission failed. I didn't receive this, but I sensed its absence."],
  },
  footer: {
    taglines: ["Available for hire. Will discuss anything.", "Crafting synergy since [YEAR].", "All rights reserved. Skills open source.", "This website was built with passion and free stock components."],
    copyright_suffixes: ["All previous employers respected.", "References available (2 of 3 confirmed real).", "No animals were harmed in the making of this portfolio."],
    legal_micro_text: ["Skills listed are self-assessed and may differ from external assessment. Experience years calculated using a proprietary formula. Client count includes projects that reached 'almost done' stage."],
  },
  nav: { link_labels: ["About (Me)", "Skills (Mine)", "Work (Good)", "Contact (Do It)", "Resume (Download)", "Blog (Coming Soon)", "Pricing (Ha)"] },
  trust_bar: {
    section_titles: ["As Featured In", "Media Coverage", "Industry Recognition", "They Wrote About Me (Broadly Speaking)"],
    logo_names: ["ProfessionalQuarterly", "LinkedInPulse™", "The Recruiter's Friend", "IndeedInsider", "HireWire Magazine", "TalentBuzz Daily", "CoverLetterWeekly"],
  },
  cta_banner: {
    headlines: ["Ready to Work Together?", "Your Team Needs This.", "One Hire Can Change Everything."],
    subtext: ["Let's schedule a call, a meeting, or a coffee chat. I bring the coffee (mine)."],
    cta_texts: ["Book Intro Call", "Send Email Now", "View Full CV", "I'm Ready"],
  },
};
