import type { ContentPools } from "./content-pools";

export const startupContent: ContentPools = {
  hero: {
    headlines: [
      "The Last [NOUN] Software You'll Ever Need (Until The Next One)",
      "We Used AI To Make This. We're Not Sure How.",
      "Disrupting [INDUSTRY] With Technology And Confidence",
      "10× Your [METRIC] Or We'll Look Into Why Not",
      "Enterprise-Grade [THING] For Teams Of 1 To Infinity",
      "The Platform That [VERB]s Your [NOUN]s Automatically",
      "Finally. [THING] That Just Works. (Terms Apply.)",
    ],
    subheadlines: [
      "Trusted by 10,000+ teams. 9,847 of them still active.",
      "Powered by AI, ML, blockchain, and confidence.",
      "Join the waitlist. There is no waitlist. Join anyway.",
      "99.97% uptime SLA. The 0.03% is scheduled for your timezone.",
      "No credit card required. Card required after 14 days. Card is definitely required.",
      "Used by teams at companies you've heard of, and also ours.",
      "The #1 platform in our category (category defined by us for this purpose).",
    ],
    cta_primary: [
      "Start Free Trial (Card Required Eventually)",
      "Get Started For Free (Nothing Is Free)",
      "Try It Now — No Setup Required (Some Setup Required)",
      "See It In Action (Action May Vary)",
      "Book A Demo (With Our Best Demo Person)",
    ],
    cta_secondary: [
      "Watch 47-Minute Product Tour",
      "Read 94-Page Whitepaper",
      "See Pricing (If You're Sure)",
      "Talk To Sales (They Are Ready)",
    ],
    badge_texts: [
      "🚀 NOW WITH AI",
      "✅ SOC2 COMPLIANT (PENDING)",
      "🏆 G2 LEADER (SELF-NOMINATED)",
      "⚡ SERIES A CLOSING SOON",
      "🔒 ENTERPRISE READY",
    ],
  },
  features: {
    section_titles: [
      "Everything You Need And Several Things You Don't",
      "Powerful Features That Will Transform How You Work (Allegedly)",
      "The Complete Solution (Completeness May Vary By Plan)",
      "Why Teams Choose Us (And Then Sometimes Switch)",
    ],
    card_headlines: [
      "AI-Powered Everything",
      "Real-Time Collaboration",
      "Enterprise Security",
      "Seamless Integrations",
      "Advanced Analytics",
      "Automated Workflows",
      "Unlimited Scalability",
      "24/7 Support (Business Hours)",
    ],
    card_bodies: [
      "Our AI analyzes your data and produces outputs. We're still documenting what kind of outputs.",
      "Work with your team in real-time, or alone in real-time, which is just regular time.",
      "Bank-grade security using the same encryption everyone else uses. Banks included.",
      "Connects with 500+ tools you already have and 200+ tools you'll need to buy separately.",
      "Dashboard with charts, graphs, and numbers. The numbers are real. The insights are extra.",
      "Automate any workflow you can describe in 3 words or fewer. More words available on Enterprise.",
      "Scales from 1 user to enterprise. Enterprise pricing available upon awkward phone call.",
      "Support team available 24/7, Monday through Friday, 9am to 5pm Eastern.",
    ],
    card_icons_labels: ["🤖 AI (undefined)", "⚡ Fast (relative to what we had before)", "🔒 Secure (mostly)"],
  },
  testimonials: {
    section_titles: ["What Customers Are Saying (The Good Ones)", "Success Stories (Case Studies Pending)", "Don't Take Our Word For It (But Please Do)"],
    quotes: [
      "We switched from [COMPETITOR] and haven't switched back yet. That's something.",
      "Our team's productivity increased by a metric that looked good in the report.",
      "The onboarding took 3 weeks, but the other 3 weeks have been mostly fine.",
      "I showed it to our VP and she asked several questions we're still answering.",
      "Worth every penny of the money we're spending on it. Still calculating the exact amount.",
      "Honestly, better than expected given what we expected.",
      "The support team was very understanding about all our questions.",
      "We use it every day now. Or most days. The important ones.",
      "Game-changer. Our definition of 'game' has changed as a result.",
    ],
    names: ["Sarah K.", "Michael T.", "Jennifer L., VP", "David (not his real name)", "Aisha R.", "Bob Something", "A Customer"],
    titles: ["Head of Ops", "CTO (Acting)", "Director of Digital Stuff", "Co-Founder, CXO, CBDO", "Enterprise Customer"],
    companies: ["ScaleFast Inc.", "GrowthCo.", "Pivot LLC", "Disruption Holdings", "The Company", "A Fortune 500 (500th-ish)"],
    star_captions: ["⭐⭐⭐⭐⭐ on G2 (screenshot available)", "4.9★ App Store (6 reviews)", "★★★★★ self-reported on homepage"],
  },
  about: {
    section_titles: ["Our Story (The Compelling Version)", "Why We Built This", "The Mission"],
    paragraphs: [
      "We founded [COMPANY] after experiencing the pain of not having [PRODUCT] ourselves. The problem was obvious in retrospect, which is our favorite kind of obvious. We spent 18 months building what we thought users wanted, talked to 3 actual users, and rebuilt it entirely.",
      "Our mission is to [VERB] the way [TARGET_AUDIENCE] [VERB]s [NOUN]. We believe that [INDUSTRY] is broken (we checked), and that the solution is more software. We are that software. We are also more than software. We are a platform.",
      "Started in a garage. (The garage has been upcycled into a 'collaborative workspace studio'.) Funded by a mixture of angel investment, personal credit cards, and optimism.",
    ],
  },
  stats: {
    labels: ["Active Users", "Data Points Processed", "Time Saved Per User", "Integrations", "Countries", "NPS Score"],
    values: ["10,847+", "∞ (estimate)", "4.7 hrs/week", "500+", "47", "72 (industry avg: 41)"],
    captions: ["*active = logged in once", "*we stopped counting", "*self-reported", "*planned or live", "*where our server is accessible", "*sample: 12"],
  },
  faq: {
    section_titles: ["Frequently Asked Questions", "Things You're Probably Wondering"],
    questions: ["How is this different from [COMPETITOR]?", "Is there a free trial?", "What happens to my data?", "Do you have an API?", "Can I cancel anytime?", "Is this GDPR compliant?", "Do you offer discounts?"],
    answers: ["Great question. We are different in several ways that our marketing team is finalizing.", "Yes! 14 days. Credit card required. The card is charged on day 15. We remind you on day 14 (afternoon).", "Your data is stored securely in the cloud, which is another company's server. We have agreements about this.", "Yes. Our API is documented. Most of the documentation is accurate.", "Yes, you can cancel anytime. Cancellation initiates a 30-day offboarding process.", "GDPR compliant to the best of our knowledge, which is improving every quarter.", "Startups and nonprofits receive special consideration, which is to say, we talk about it with them."],
  },
  form: {
    section_titles: ["Start Your Free Trial", "Get Early Access", "Book A Demo", "Talk To Our Team"],
    field_labels: ["Work Email", "Company Name", "Company Size", "How'd You Hear About Us?", "What Are You Hoping To Solve?"],
    placeholders: ["you@company.com (personal emails redirected)", "Your Company Inc.", "1–10 / 11–50 / 51–200 / 201–500 / 500+ / Won't Say", "Google / LinkedIn / A dream", "Describe in 10,000 characters or fewer"],
    submit_texts: ["Get Started Free", "Book Demo", "Talk To Sales", "Unlock Access", "Start Disrupting"],
    success_messages: ["You're in! Expect an email in 3–5 business days. Or sooner. Definitely within a business quarter.", "Thanks! A member of our team will reach out when they finish what they're working on.", "Welcome to the waitlist! You are number [NUMBER]. The list moves quickly. Relatively."],
    error_messages: ["We couldn't process your request. Our system is experiencing growth pains.", "Something went wrong. This is embarrassing and being investigated.", "Error 500: An internal error occurred."],
  },
  footer: {
    taglines: ["Making [INDUSTRY] better, one subscription at a time.", "Built with passion. Powered by VC funding.", "© [YEAR] [COMPANY]. All rights reserved. All lefts also reserved."],
    copyright_suffixes: ["Funding: Series A (closing soon, has been closing for 6 months).", "Registered in Delaware for tax reasons."],
    legal_micro_text: ["Use of this platform constitutes acceptance of terms that are available on a separate page that requires 3 clicks to find. Analytics, telemetry, and behavioral data collected."],
  },
  nav: { link_labels: ["Product", "Pricing (Blurred)", "Enterprise (Call Us)", "About", "Blog", "Sign In", "Start Free →"] },
  trust_bar: {
    section_titles: ["Trusted By Forward-Thinking Teams", "As Seen In", "Used By People Who Work"],
    logo_names: ["TechCrunch (mentioned in comment)", "ProductHunt #1 of the Day", "Hacker News (briefly)", "Forbes (we linked to them)", "The Verge (they don't know)", "G2 Leader (self-nominated)"],
  },
  cta_banner: {
    headlines: ["Ready To Transform How Your Team Works?", "Still On The Old Way Of Doing Things?", "Your Competitors Are Already Using Us."],
    subtext: ["Join 10,000+ teams who already made the switch.", "Don't let your team fall behind because you didn't sign up for a free trial.", "True. Statistically. At least one of them is."],
    cta_texts: ["Start Free Trial", "Book Demo Now", "See Pricing", "Join Waitlist"],
  },
};
